################################
## Astronomer Ingress
#################################
{{- if .Values.global.baseDomain }}
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: {{ .Release.Name }}-public-ingress
  labels:
    component: public-ingress
    tier: astronomer
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
  annotations:
  {{- range $key, $value := .Values.global.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($host = '{{ .Values.global.baseDomain }}' ) {
        rewrite ^ https://app.{{ .Values.global.baseDomain }}$request_uri permanent;
      }
spec:
  tls:
{{ toYaml .Values.global.ingress.tls | indent 4 }}
  rules:
  - host: app.{{ .Values.global.baseDomain }}
    http:
      paths:
        - path: /
          backend:
            serviceName: {{ .Release.Name }}-orbit
            servicePort: orbit-http
  - host: houston.{{ .Values.global.baseDomain }}
    http:
      paths:
        - path: /
          backend:
            serviceName: {{ .Release.Name }}-houston
            servicePort: houston-http
  - host: registry.{{ .Values.global.baseDomain }}
    http:
      paths:
        - path: /
          backend:
            serviceName: {{ .Release.Name }}-registry
            servicePort: registry-http
  - host: install.{{ .Values.global.baseDomain }}
    http:
      paths:
        - path: /
          backend:
            serviceName: {{ .Release.Name }}-cli-install
            servicePort: install-http
{{ end }}
