################################
## Commander NetworkPolicy
#################################
{{ if .Values.global.enableNetworkPolicies }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-commander-policy
  labels:
    tier: astronomer
    component: commander-policy
    release: {{ .Release.Name }}
    workspace: {{ .Values.workspace }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
spec:
  podSelector:
    matchLabels:
      tier: astronomer
      component: commander
      release: {{ .Release.Name }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          tier: astronomer
          release: {{ .Release.Name }}
          component: houston
    ports:
    - protocol: TCP
      port: {{ .Values.ports.commanderGRPC }}
{{ end }}
