# Default values for astronomer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# User in pilot containers
uid: 100

global:
  enableNetworkPolicies: false

# Images for pilot
images:
  commander:
    repository: astronomerinc/ap-commander
    tag: 0.7.5
    pullPolicy: IfNotPresent
  registry:
    repository: astronomerinc/ap-registry
    tag: 0.7.5
    pullPolicy: IfNotPresent
  houston:
    repository: astronomerinc/ap-houston-api
    tag: 0.7.5
    pullPolicy: IfNotPresent
  orbit:
    repository: astronomerinc/ap-orbit-ui
    tag: 0.7.5
    pullPolicy: IfNotPresent
  dbBootstrapper:
    repository: astronomerinc/ap-db-bootstrapper
    tag: 0.7.5
    pullPolicy: IfNotPresent
  cliInstall:
    repository: astronomerinc/ap-cli-install
    tag: 0.7.5
    pullPolicy: IfNotPresent

smtp:
  uri: ~

auth:
  local:
    enabled: true
  google:
    enabled: true
    clientId: ~
  auth0:
    enabled: true
    clientId: "rH2L4yKctlepniTyJW3MkuXuTreOHHn1"
    baseDomain: "astronomerio.auth0.com"
    externalLogin: false
  github:
    enabled: true

orbit:
  env: {}
  resources: {}
  #  limits:
  #   cpu: 100m
  #   memory: 128Mi
  #  requests:
  #   cpu: 100m
  #   memory: 128Mi

houston:
  # Houston datastore
  backendSecretName: ~
  backendConnection: {}
    # user: ~
    # pass: ~
    # host: ~
    # port: ~
    # db: ~
  # Airflow backends
  airflowBackendSecretName: ~
  airflowBackendConnection: {}
    # user: ~
    # pass: ~
    # host: ~
    # port: ~
    # db: ~

  env: {}
  resources: {}
  #  limits:
  #   cpu: 100m
  #   memory: 128Mi
  #  requests:
  #   cpu: 100m
  #   memory: 128Mi

commander:
  env: {}
  resources: {}
   # limits:
   #  cpu: 100m
   #  memory: 128Mi
   # requests:
   #  cpu: 100m
   #  memory: 128Mi

registry:
  resources: {}
  #  limits:
  #   cpu: 100m
  #   memory: 128Mi
  #  requests:
  #   cpu: 100m
  #   memory: 128Mi

  persistence:
    # Enable persistent storage
    enabled: true
    # Size of volume to provision
    size: 100Gi
    # If using a custom storageClass, pass name ref to all statefulSets here
    storageClassName: ~

  auth:
    secretName: ~
    connection: ~
    service: "docker-registry"
    issuer: "houston"


install:
  resources: {}
  #  limits:
  #   cpu: 100m
  #   memory: 128Mi
  #  requests:
  #   cpu: 100m
  #   memory: 128Mi

ports:
  houstonHTTP: 8870
  commanderHTTP: 8880
  commanderGRPC: 50051
  orbitHTTP: 8080
  registryHTTP: 5000
  registryScrape: 5001
  installHTTP: 80
